method: bayes
metric: {"name": "loss", "goal": "minimize"}
parameters: {
  ent_coef: {"min": 0.001, "max": 0.1},
  vf_coef: {"min": 0.1, "max": 1.0},
  lr: {"min": 0.0001, "max": 0.01},
  clip_coef: {"min": 0.1, "max": 0.3},
  gamma: {"min": 0.9, "max": 0.99},
  batch_size: {"min": 16, "max": 128},
  project_name: BachlorThesis_MPE,
}

train: True,
track: True,
render: True,
save_model: True,
max_cycles: 100,
total_episodes: 100,

