program: test.py
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  ent_coef: 
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  vf_coef: 
    values: [0.5, 0.6, 0.7, 0.8, 0.9]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}